apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-connect-config
data:
  HADOOP_USER_NAME: "root"
  CONNECT_BOOTSTRAP_SERVERS: "kafka:9092"
  CONNECT_REST_PORT: "8083"
  CONNECT_GROUP_ID: "kafka-connect-group-id-01"
  CONNECT_CONFIG_STORAGE_TOPIC: "_connect-configs"
  CONNECT_OFFSET_STORAGE_TOPIC: "_connect-offsets"
  CONNECT_STATUS_STORAGE_TOPIC: "_connect-status"
  CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
  CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
  CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
  CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components,/data/connect-jars"
  CONNECT_KEY_CONVERTER: "io.confluent.connect.avro.AvroConverter"
  CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: "http://kafka-schema-registry:8081"
  CONNECT_VALUE_CONVERTER: "io.confluent.connect.avro.AvroConverter"
  CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://kafka-schema-registry:8081"
  CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
  CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-connect-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-connect
  template:
    metadata:
      labels:
        app: kafka-connect
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
      volumes:
        - name: kafka-connect-pv-storage
          persistentVolumeClaim:
            claimName: kafka-connect-pvc
      containers:
        - name: kafka-connect
          image: registry.gitlab.sdu.dk/jah/bigdatarepo/kafka-connect:7.3.1
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - mountPath: "/data/"
              name: kafka-connect-pv-storage
          envFrom:
            - configMapRef:
                name: kafka-connect-config
          env:
            - name: CONNECT_REST_ADVERTISED_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-connect
spec:
  type: NodePort
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    app: kafka-connect