apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-schema-registry-config
data:
  SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "kafka:9092"
  SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-schema-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-schema-registry
  template:
    metadata:
      labels:
        app: kafka-schema-registry
    spec:
      containers:
        - name: kafka-schema-registry
          image: confluentinc/cp-schema-registry:7.3.1
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: kafka-schema-registry-config
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-schema-registry
spec:
  selector:
    app: kafka-schema-registry
  ports:
    - name: web
      protocol: TCP
      port: 8081
      targetPort: 8081