apiVersion: v1
kind: ConfigMap
metadata:
  name: redpanda-config
data:
  KAFKA_BROKERS: "kafka:9092"
  KAFKA_SCHEMAREGISTRY_ENABLED: "false"
  KAFKA_SCHEMAREGISTRY_URLS: "http://kafka-schema-registry:8081"
  CONNECT_ENABLED: "true"
  CONNECT_CLUSTERS_NAME: "Connectors"
  CONNECT_CLUSTERS_URL: "http://kafka-connect:8083"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      containers:
        - name: redpanda
          image: redpandadata/console:v2.7.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: redpanda-config
---
apiVersion: v1
kind: Service
metadata:
  name: redpanda
spec:
  selector:
    app: redpanda
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080