apiVersion: v1
kind: ConfigMap
metadata:
  name: sqoop-config
data:
  core-site.xml: |
    <?xml version="1.0"?>
    <configuration>
        <property>
            <name>fs.defaultFS</name>
            <value>hdfs://namenode:9000</value>
        </property>
    </configuration>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqoop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqoop
  template:
    metadata:
      labels:
        app: sqoop
    spec:
      containers:
        - name: sqoop
          image: dvoros/sqoop:latest
          envFrom:
            - configMapRef:
                name: sqoop-config
          volumeMounts:
            - name: sqoop-config-volume
              mountPath: /usr/local/hadoop/etc/hadoop/core-site.xml
              subPath: core-site.xml
          command: ["/bin/bash", "-c", "--"]
          args:
            - >
              sed -i 's|^mirrorlist=|#mirrorlist=|g' /etc/yum.repos.d/CentOS-Base.repo &&
              sed -i 's|^#baseurl=http://mirror.centos.org/centos/$releasever|baseurl=http://vault.centos.org/centos/7.9.2009|g' /etc/yum.repos.d/CentOS-Base.repo &&
              yum clean all &&
              yum install -y postgresql &&
              curl -L -o /usr/local/sqoop/lib/postgresql-42.2.24.jar https://jdbc.postgresql.org/download/postgresql-42.2.24.jar &&
              tail -f /dev/null;
          env:
            - name: HADOOP_CLASSPATH
              value: "/usr/local/sqoop/lib/postgresql-42.2.24.jar"
      volumes:
        - name: sqoop-config-volume
          configMap:
            name: sqoop-config
            items:
              - key: core-site.xml
                path: core-site.xml
---
apiVersion: v1
kind: Service
metadata:
  name: sqoop
spec:
  selector:
    app: sqoop
  ports:
    - protocol: TCP
      port: 12000
      targetPort: 12000